document.writeln("<!-- Baidu Button BEGIN -->");
document.writeln("<div id=\"bdshare\" class=\"bdshare_t bds_tools get-codes-bdshare\">");
document.writeln("<a class=\"bds_qq\">QQ收藏<\/a>");
document.writeln("<a class=\"bds_sqq\">QQ好友<\/a>");
document.writeln("<a class=\"bds_tsina\">新浪微博<\/a>");
document.writeln("<a class=\"bds_qzone\">QQ空间<\/a>");
document.writeln("<a class=\"bds_tqq\">腾讯微博<\/a>");
document.writeln("<a class=\"bds_renren\">人人网<\/a>");
document.writeln("<a class=\"bds_t163\">网易微博<\/a>");
document.writeln("<a class=\"bds_baidu\">百度搜藏<\/a>");
document.writeln("<a class=\"bds_mshare\">一键分享<\/a>");
document.writeln("<a class=\"bds_tieba\">百度贴吧<\/a>");
document.writeln("<a class=\"bds_kaixin001\">开心网<\/a>");
document.writeln("<a class=\"bds_copy\">复制网址<\/a>");
document.writeln("<span class=\"bds_more\">更多<\/span>");
document.writeln("<\/div>");
document.writeln("<script type=\"text\/javascript\" id=\"bdshare_js\" data=\"type=tools&amp;uid=6814063\" ><\/script>");
document.writeln("<script type=\"text\/javascript\" id=\"bdshell_js\"><\/script>");
document.writeln("<script type=\"text\/javascript\">");
document.writeln("document.getElementById(\"bdshell_js\").src = \"http:\/\/bdimg.share.baidu.com\/static\/js\/shell_v2.js?cdnversion=\" + Math.ceil(new Date()\/3600000);");
document.writeln("<\/script>");
document.writeln("<!-- Baidu Button END -->");