<?php
/**
 * 主配置文件
 * 调用方式：Yii::app()->controller->module['xxx']
 */
return array(
    'admin' => array(
        'list_count' => 50, // 默认后台列表展示条数
    ),
    'blocktype'=>array(
    	'novel'=>'小说区块',
    	//'user'=>'用户区块',
    	//'comment'=>'评论区块',
    	//'self'=>'自定义区块'
    ),
    'blockstatus'=>array(
    	'1'=>'不显示',
    	'2'=>'登陆前显示',
    	'3'=>'登录后显示',
    	'4'=>'都显示'
    ),
    'sorttype'=>array(
    	'1'=>'总点击',
    	'2'=>'月点击',
    	'3'=>'周点击',
    	'4'=>'日点击',
    	'5'=>'总推荐',
    	'6'=>'月推荐',
    	'7'=>'周推荐',
    	'8'=>'日推荐',
    	'9'=>'最新入库',
    	'10'=>'收藏数',
    	'11'=>'文章字数',
    	'12'=>'最新更新',
    	'13'=>'本站推荐'
    ),
    'order'=>array(
    	'1'=>'由小到大',
    	'2'=>'由大到小',
    ),
    'templatetags'=>array(
    	'{$block.id}'=>'小说id',
    	'{$block.title}'=>'小说标题',
    	'{$block.author}'=>'小说作者',
    	'{$block.authorid}'=>'作者id',
    	'{$block.cid}'=>'分类ID',
    	'{$block.flag}'=>'全本状态',
    	'{$block.keywords}'=>'关键词',
    	'{$block.summary}'=>'简介',
    	'{$block.pinyin}'=>'小说拼音',
    	'{$block.initial}'=>'首字母',
    	'{$block.recommendlevel}'=>'推荐等级',
    	'{$block.favoritenum}'=>'收藏数',
    	'{$block.wordcount}'=>'字数',
    	'{$block.lastchapterid}'=>'最新章节ID',
    	'{$block.lastchaptertitle}'=>'最新章节标题',
    	'{$block.lastchaptertime}'=>'最后更新章节时间',
    	'{$block.alllikenum}'=>'推荐总数',
    	'{$block.monthlikenum}'=>'月推荐数',
    	'{$block.weeklikenum}'=>'周推荐数',
    	'{$block.daylikenum}'=>'日推荐数',
    	'{$block.allclicks}'=>'总点击数',
    	'{$block.monthclicks}'=>'月点击数',
    	'{$block.weekclicks}'=>'周推荐数',
    	'{$block.dayclicks}'=>'日推荐数',
    	'{$block.hascover}'=>'封面状态',
    	'{$block.createtime}'=>'入库时间',
    ),
    'front' => array(
    ),
);